### ISSUE TITLE
BGM SideA/SideB 동시 추출 불가

### ISSUE THREAD

**Issue by Lastorder-DC** [36base/girlsfrontline-resources-extract#2]
```
INFO | Start Extracting : 2018-08-06 11:47:28
INFO | === ACB File: GF_MAP4_BGM.acb.bytes ===
afs2: 2 files in ar
afs2: aligned to 32 bytes
afs2: a file offset is 4 bytes
INFO | GF_MAP4_BGM
INFO | Finish Extracting : 2018-08-06 11:47:29


=== 소모시간 : 0.934004545211792초 ===
```
곡 자체는 두곡 모두 인식하는것 같지만 실제로는 하나만 추출됩니다.

**Comment by krepe-suZette** [comment]
![image](https://user-images.githubusercontent.com/37508580/43727324-93af32d4-99dc-11e8-8f90-08696c36e7d1.png)

acb 파일에서 hca 파일로 변환하는 과정은 [acb.py](https://github.com/summertriangle-dev/acb.py) 를 사용하고 있습니다. 동일 파일을 넣어서 디버깅을 좀 해봤는데, 음악 데이터는 확실히 있는데 `name`이나 `cue id` 같은 정보를 못찾아서(또는 해당 정보 자체가 없어서) 그런거같네요. 위 사진의 `data_source.files` 를 보면 파일이 두개인걸로 보이는데 `cue.tracks`를 보면 하나밖에 안보여요.

아무튼 해결을 하려면 시간이 좀 걸릴 것 같습니다. 갯수 확인해서 강제로 뽑아내게 하면 될거같긴 한데, 확신이 안서네요.
