### ISSUE TITLE
BGM 추출시 hca 파일로 추출 옵션

### ISSUE THREAD

**Issue by Lastorder-DC** [36base/girlsfrontline-resources-extract#7]
hca 파일로 추출시 [vgmstream](https://hcs64.com/vgmstream.html)을 이용해서 반복 재생 등을 사용할수 있습니다.

**Comment by krepe-suZette** [comment]
https://github.com/36base/girlsfrontline-resources-extract/releases/tag/v2.0.3
추가했습니다. config.ini 파일 안의 `save_wav` 값을 false로 바꿔주면 별도 처리 과정 없이 hca로 바로 저장될거에요.
