### ISSUE TITLE
파일 추출 경로 별도 지정 가능하게 변경

### ISSUE THREAD

**Issue by krepe-suZette** [36base/girlsfrontline-resources-extract#9]
`config_dir.json` 에서 설정값들을 불러온 다음 해당 경로에 추출하는 방향으로 변경할 예정
`master_extract_dir` key에 전역 경로 지정 기능 추가 예정. 가능하면 girlsfrontline-resources 에 바로 꽂아넣는 방식이 될 수 있도록 하는것을 목표로 함.

**Comment by CirnoV** [comment]
`-o, --output`옵션으로 직접 지정하게 했으면 좋겠음

https://docs.python.org/ko/3/howto/argparse.html 아마 이거 참고하면 될듯?
